// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server_side

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerSideClient is the client API for ServerSide service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerSideClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (ServerSide_GetUserClient, error)
}

type serverSideClient struct {
	cc grpc.ClientConnInterface
}

func NewServerSideClient(cc grpc.ClientConnInterface) ServerSideClient {
	return &serverSideClient{cc}
}

func (c *serverSideClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (ServerSide_GetUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServerSide_ServiceDesc.Streams[0], "/server_side.ServerSide/GetUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverSideGetUserClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerSide_GetUserClient interface {
	Recv() (*GetUserResponse, error)
	grpc.ClientStream
}

type serverSideGetUserClient struct {
	grpc.ClientStream
}

func (x *serverSideGetUserClient) Recv() (*GetUserResponse, error) {
	m := new(GetUserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerSideServer is the server API for ServerSide service.
// All implementations must embed UnimplementedServerSideServer
// for forward compatibility
type ServerSideServer interface {
	GetUser(*GetUserRequest, ServerSide_GetUserServer) error
	mustEmbedUnimplementedServerSideServer()
}

// UnimplementedServerSideServer must be embedded to have forward compatible implementations.
type UnimplementedServerSideServer struct {
}

func (UnimplementedServerSideServer) GetUser(*GetUserRequest, ServerSide_GetUserServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedServerSideServer) mustEmbedUnimplementedServerSideServer() {}

// UnsafeServerSideServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerSideServer will
// result in compilation errors.
type UnsafeServerSideServer interface {
	mustEmbedUnimplementedServerSideServer()
}

func RegisterServerSideServer(s grpc.ServiceRegistrar, srv ServerSideServer) {
	s.RegisterService(&ServerSide_ServiceDesc, srv)
}

func _ServerSide_GetUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerSideServer).GetUser(m, &serverSideGetUserServer{stream})
}

type ServerSide_GetUserServer interface {
	Send(*GetUserResponse) error
	grpc.ServerStream
}

type serverSideGetUserServer struct {
	grpc.ServerStream
}

func (x *serverSideGetUserServer) Send(m *GetUserResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ServerSide_ServiceDesc is the grpc.ServiceDesc for ServerSide service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerSide_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_side.ServerSide",
	HandlerType: (*ServerSideServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUser",
			Handler:       _ServerSide_GetUser_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/server_side/server_side.proto",
}
